### ISSUE TITLE
non-standard import ...... in standard package

### ISSUE THREAD

**Issue by 2994186010** [ryanphuang/panorama#4]
After executing the command "make" , some errors are returned, as is following:
mkdir -p build/gen
protoc -I=idl --go_out=plugins=grpc:build/gen idl/*.proto 
go get ./...
/usr/local/go/src/panorama/build/gen/health.pb.go:8:2: non-standard import "github.com/golang/protobuf/proto" in standard package "panorama/build/gen"
/usr/local/go/src/panorama/types/health.go:12:2: non-standard import "github.com/golang/protobuf/ptypes" in standard package "panorama/types"
/usr/local/go/src/panorama/decision/majority.go:4:2: non-standard import "github.com/golang/protobuf/ptypes/timestamp" in standard package "panorama/decision"
/usr/local/go/src/panorama/exchange/exchange.go:7:2: non-standard import "github.com/golang/protobuf/ptypes" in standard package "panorama/exchange"
/usr/local/go/src/panorama/service/service.go:8:2: non-standard import "github.com/golang/protobuf/ptypes" in standard package "panorama/service"
/usr/local/go/src/panorama/store/raw.go:13:2: non-standard import "github.com/golang/protobuf/ptypes" in standard package "panorama/store"
make: *** [get] Error 1

**Comment by ryanphuang** [comment]
Hi,

You probably mixed up your GOROOT and GOPATH setting. The project should be cloned into $GOPATH (https://github.com/golang/go/wiki/GOPATH) not $GOROOT (which contains the standard go libraries). Let me know if that resolves the error.

**Comment by 2994186010** [comment]
I have tried your suggestion and still fail. I re-install the os system and try the step you list in the README.md in a new environment. Finally, I success.
